[versions]

agp = "8.13.2"
camposer = "1.0.0"
kotlin = "2.3.0"
compose-multiplatform = "1.11.0-alpha01"

compose-bom = "2025.12.01"
exoplayer = "2.19.1"
zxing = "3.5.4"
cloudy = "0.4.0"
appcompat = "1.12.2"
material = "1.13.0"
lifecycle = "2.10.0"
navigation = "2.9.6"
kotlinx-serialization = "1.9.0"
accompanist = "0.37.3"
coil = "2.7.0"
koin = "4.1.1"
datastore = "1.2.0"
camera-core = "1.5.2"

# kmp
media-kmp = "2.0.6"
kotlinx-io = "0.8.0"

[libraries]

camposer = { module = "io.github.ujizin:camposer", version.ref = "camposer" }
camposer-code-scanner = { module = "io.github.ujizin:camposer-code-scanner", version.ref = "camposer" }
material = { module = "com.google.android.material:material", version.ref = "material" }
koin = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "appcompat" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-runtime-android = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation-android = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material:material" }
compose-material3-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }

zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
cloudy = { module = "com.github.skydoves:cloudy", version.ref = "cloudy" }

kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
media-kmp = { module = "io.github.khubaibkhan4:mediaplayer-kmp", version.ref = "media-kmp" }

## KMP Compose
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }

[bundles]

compose = [
  "compose-runtime-android",
  "compose-ui",
  "compose-tooling-preview",
  "compose-ui-tooling",
  "compose-foundation-android"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }